matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-dev
            - libjpeg-dev
            - libqt4-dev
            - libpng-dev
            - libtiff-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-dev
            - libjpeg-dev
            - libqt4-dev
            - libpng-dev
            - libtiff-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - make